// Programmsymbol und Startprotokoll der Oberfläche (ab v2.6, Roadmap v2.5)
//
// AppSymbol: blaues L als Rakete (Quelle: src\Oberflaeche\Symbol.ico, Entwürfe in Doku\Symbol). Startet die Oberfläche aus
// LeosMinibench.exe, kommt das Symbol aus der exe, sonst aus der hier eingebetteten Kopie. Eine eigene
// AppUserModelID trennt das Fenster in der Taskleiste von PowerShell, damit dort das eigene Symbol erscheint.
//
// StartLog: Zeitstempel je Startphase. LeosMinibench.exe legt eine Statusdatei im lokalen TEMP an und nennt sie über
// die Umgebungsvariable LEOSMINIBENCH_START; Skript und Oberfläche hängen ihre Phasen an. Ist die Oberfläche
// gezeichnet, schreibt StartLog den Block einmal nach Minibench-Daten\Laufzeit\Start.log und gibt dem Startfenster der
// exe über das benannte Ereignis LEOSMINIBENCH_BEREIT das Zeichen zum Schließen.
public static class AppSymbol
{
    [System.Runtime.InteropServices.DllImport("shell32.dll", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
    static extern int SetCurrentProcessExplicitAppUserModelID(string appId);

    public const string AppId = "LeosMinibench.Oberflaeche";

    public const string Ico =
        "AAABAAcAEBAAAAEAIABoBAAAdgAAABgYAAABACAAiAkAAN4EAAAgIAAAAQAgAKgQAABmDgAAMDAAAAEAIACoJQAADh8AAEBAAAABACAAKEIAALZEAACAgAAAAQAgAPYQAADehgAAAAAAAAEAIACoJQ" +
        "AA1JcAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/gAAC62MldOpjJcfqYCIlAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAADOZ/wU8kvvJPJL8lkCP/xDuZiIe62Mlv+tjJf/rYyX/62MmzP9mMwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzmf8KPqb7/UXP/P+Biqrw6WQo8+tjJf/rYyX/" +
        "62Ml/+tjJf/rZCVZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFeT29nHa0P/6mMl/+tjJf/rYyX/62Ml/+tjJf/qYyWt7VskDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOZmMwrZUSD82E4d/+" +
        "FYIP/rYyX/62Ml/+tjJfLqYyRiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3lYgqthOHf/YTh3/5l4j/+tjJf/rYiXX5mYaCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAP8AAALcUx/p2E4d/9pQHv/pYSX/62Ml/+pjJJMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4VseKtpQHf3YTh3/4FYg/+tjJf/rYyX+6mQmSgAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhVSCH2E4d/9hOHf/lXCL/62Ml/+tjJebyXigTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN5UINrYTh3/2U8d/+lh" +
        "JP/rYyX/6mMloAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfYCAY21Ef+thOHf/eVB//62Ml/+tjJf3sZiYoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAN9ZIGfZTh3/2E4d/+NaIv/rYyX/6mImegAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA31ggndhOHf/YTx3/518k/+xiJZ4AAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADfViB52lEe+dtSH//rYySbAAAAAAAAAAAAAAAA//8AAP//AAD+HwAAwA8AAMAPAADgDwAAwD8AAOA/AADgPwAA8B8AAPgPAAD8DwAA/AcAAP4HAA" +
        "D/BwAA/4cAACgAAAAYAAAAMAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqYCAY62QlpOtkJbvyXigTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARo" +
        "v/CzyS+0RAj/8QAAAAAAAAAAAAAAAAAAAAAOpiJknrYyXm62Ml/+tjJf/rYyawAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJH7gDyS+/88kvv2PJP7f0Cf" +
        "/wjmZhoK7GIlketjJf/rYyX/62Ml/+tjJf/rYyX/6mMkYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJL8lkCt+/9F0fz/Pqb7/2qFwtvnZCrh62Ml/+tjJf/rYy" +
        "X/62Ml/+tjJf/rYyX/62Ml8vFjKxIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJH7ckGw/P9O3PX/mp6O/+hkKP/rYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyX/62Ml" +
        "5fFjKxIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPpH7OmaJxf/UWir/41oi/+tjJf/rYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf/sYiW462YpGQAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA31cij9lPHv/YTh3/2U8d/+hgJP/rYyX/62Ml/+tjJf/rYyX/62Ml8+tkJmYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAA4FgjUdhPHf/YTh3/2E4d/9xSHv/qYyX/62Ml/+tjJf/rYyX47GYmKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN" +
        "5VH7TYTh3/2E4d/9hOHf/hWCH/62Ml/+tjJf/rYyX/62QlfQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAATcUx7u2E4d/9hOHf/Y" +
        "Th3/5l4j/+tjJf/rYyX/62Ml++xhJTcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADiWyI12k8d/thOHf/YTh3/2lEe/+piJf/rYyX/62" +
        "Ml/+tjJdzqaisMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA31cflthOHf/YTh3/2E4d/99WIP/rYyX/62Ml/+tjJf/rZCWXAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN1TH+DYTh3/2E4d/9hOHf/lXCP/62Ml/+tjJf/rYyX/62UlTAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOZaIR/aUB782E4d/9hOHf/ZUB7/6WEk/+tjJf/rYyX/62Ml6OZmJhQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhVyFt2E4d/9hOHf/YTh3/3lQf/+tjJf/rYyX/62Ml/+piJJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAA3VQfzNhOHf/YTh3/2E4d/+NaIf/rYyX/62Ml/+tjJfvrZSgmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "21skDttSHvfYTh3/2E4d/9hPHf/nXyT/62Ml/+tjJf/rYyR+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOJWIFDaTh7+2E4d/9" +
        "hOHf/cUh7/6mMl/+tjJf/rYyTLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgViF92E4d/9hOHf/YTh3/4Vgh/+tjJf/r" +
        "YyXoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4FcfitlPHf7YTh3/2E4d/+deI//rYyX4AAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN5VHkXdUx/h2E4d/9pRHv/qYSXfAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP//" +
        "/wD/8P8A8eD/APAAfwDwAD8A8AA/APAAfwDwAf8A8AP/APgD/wD4Af8A/AD/AP4A/wD/AH8A/wA/AP+APwD/wB8A/8AfAP/gHwD/8B8A//gfAP/8HwAoAAAAIAAAAEAAAAABACAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOxjJkPrZCW762Mllv9VKwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAONVHAnsYiWR62Ml/utjJf/rYyX/7GIlkQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAPZP7hjyS+7w9k/pxN5L/DgAAAAAAAAAAAAAAAAAAAADuYyMs62Ml0OtjJf/rYyX/62Ml/+tjJf/rYyX+6mImSQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2S/xU8kvv/PJL7/zyS+/88kvvnO5H8XwAAAAD/AAAB6mMlb+tjJfjrYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyXl8l4oEwAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPI/4IjyS+/9Bs/z/RdH8/0Cw/P88kvv/W4rXt+hkKcXrYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf" +
        "/qZCShAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5jv8JPJL7/EPB/P9H4P3/R+D9/4Kkrv/hZjH/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyX/" +
        "62Ml/+tjJf/rYyX/62Ml/+tjJd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8kvvXQLT8/1zO3/+8f1v/62Ml/+tjJf/rYyX/62Ml/+" +
        "tjJf/rYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyXq7GMmQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyS/JiJfpf/2FEh/9lQHv/p" +
        "YSX/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyX/6mMluetiJxoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADjVRwS1F" +
        "gs3dhOHf/YTh3/2E4d/91UH//rYyX/62Ml/+tjJf/rYyX/62Ml/+tjJf/rYyX/62Ml9exkJGn/AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAANlZGhTaUR/52E4d/9hOHf/YTh3/2E4d/+NbIv/rYyX/62Ml/+tjJf/rYyX/62Ml/+tjJMvrYicnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN5YIV3ZTh3/2E4d/9hOHf/YTh3/2U8d/+hgI//rYyX/62Ml/+tjJf/rYyX/7GMkagAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN9VH73YTh3/2E4d/9hOHf/YTh3/3FIe/+pjJf/rYyX/62Ml/+tjJf/rYyX162InJwAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AABNtSH/DYTh3/2E4d/9hOHf/YTh3/4Vgh/+tjJf/rYyX/62Ml/+tjJf/rYybM" +
        "/2YzBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA41UgP9lPHv7YTh3/2E4d/9hOHf/ZTx7/5l4j/+" +
        "tjJf/rYyX/62Ml/+tjJf/rYyaBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA31cgodhOHf/Y" +
        "Th3/2E4d/9hOHf/aUR7/6mIk/+tjJf/rYyX/62Ml/+tjJfvtYiQ5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAA3VMe49hOHf/YTh3/2E4d/9hOHf/fViH/62Ml/+tjJf/rYyX/62Ml/+tjJd3rYicNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkVyIm2lAd/dhOHf/YTh3/2E4d/9hOHf/lXCP/62Ml/+tjJf/rYyX/62Ml/+tjJJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgWB962E4d/9hOHf/YTh3/2E4d/9lQHv/pYSX/62Ml/+tjJf/rYyX/62Ml/+pkJFQAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdVR/T2E4d/9hOHf/YTh3/2E4d/91UH//rYyX/62Ml/+tjJf/rYyX/62Il6e5mIg" +
        "8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANlZGhTaUR/52E4d/9hOHf/YTh3/2E4d/+NbIv/rYyX/" +
        "62Ml/+tjJf/rYyX/62MliQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOFWIVzZTh3/2E4d/9" +
        "hOHf/YTh3/2U8d/+hgI//rYyX/62Ml/+tjJf/rYyX46WImIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAN9VH73YTh3/2E4d/9hOHf/YTh3/3FIe/+pjJf/rYyX/62Ml/+tjJf/rZCWKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/2YABdtRH/HYTh3/2E4d/9hOHf/YTh3/4Vkh/+tjJf/rYyX/62Ml/+tjJOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3VUiPNpQHf3YTh3/2E4d/9hOHf/YTh3/514k/+tjJf/rYyX/62Ml/+9jIR8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA31kgZ9hPHf/YTh3/2E4d/9hOHf/aUR7/6mIk/+tjJf/rYyX/7GMmQwAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA31YgjthOHf/YTh3/2E4d/9hOHf/fViD/62Ml/+tjJf" +
        "/sZCVSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4VchbdpQHvzYTh3/" +
        "2E4d/9hOHf/lXCL/62Ml/+tlJUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAA5WEjHd5VH8bZTh3+2E4d/9lQHv/pYSX/62EkMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////////////4f///4H//w8A//4EAH/+AAB//gAAf/8AAH//AAD//gAB//4" +
        "AB///AA///4AH//+AA///wAP//+AB///wAP//8AD///gAf//8AD///AA///4AH///AB///wAf//+AD///wA///+AP///wD///+A/KAAAADAAAABgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALdIIjWuQyImAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMVS" +
        "sew1EmvLxMI/+1RiH+rz8eXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAPJT7dz2Z+9k/ofuCQ6H/EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANVjLVXOXSvtx1co/8FQJf+6SiL/s0Qg97JBHisAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPZz7wT6i+/8/qPz/" +
        "QLD850K2/E0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADudzMP4G4yotlnL//TYS3/zFsq/8VVJ/+/TiT/uEgi/7FCH82qVSsGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP6X7skCr/P9gw/3/WsT9/0K9/P9CxPuOVar/AwAAAAAAAAAAAAAAAPOAOkLs" +
        "eDfi5XI0/95sMf/XZi//0V8s/8pZKf/DUyb/vU0k/7ZGIf+wPx1xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQK/9f0G0/P+08v7/w/n+/5Tm/f9Mz/z/RdP+uEDf/xD/bSQH8n04jfaBO/3wfTn/6nY2/+NwM//cajD/1WQu/89dK//IVyj/wVEl/7tL" +
        "I/+1RSCXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAQLf7PEK9/P+p7v3/w/n+/8P5/v+x9P7/XOD975SwnmTvdzTS8ns3//R/Of/1gTv/7ns4/+h1Nf/hbjL/2mgw/9NiLf/NXCr/xlUn/79PJce8TiEXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQL//BEPF/OmL5v3/w/n+/8P5/v+n8vzs1YZYi+twMP" +
        "judDP/8Hg1//J8N//1gDr/8386/+x5N//mczT/32wy/9hmL//RXyz7y1opiMxmMwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEPN/ZBi3f3/v/j+/6Xb377mZSu/52ks/+ptL//scTH/7nUz//F5Nv/zfTj/9YE6//F9Of/qdzb/5HEz/9" +
        "1rMd7VZi88AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAEbX/zNJ3f3TvZB2iOFeJu3kYin/5mYr/+hqLf/qbi//7XIy/+92NP/xejb/9H45//aCO//vezj/53Q2oupqKwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN1VIg/YVCKk3Vci/+Bb" +
        "Jf/iXyf/5GMp/+dnLP/pay7/628w/+5zM//wdzX/8ns3//R/Oen1gDtOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJOyEniTsej406HtbUTh7x3FQh/95YI//gXCX/42Ao/+VkKv/naCz/6mwv/+xwMf/udDP/8Xk2" +
        "y/OAOhYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAiDkcLYo7HruKOh7+ijoe/4o6Hv+WPR7F2lEf/9xVIf/fWiT/4V4m/+NiKP/mZiv/6Got/+puL//tcjL/73Y08/F4OSQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAijoewoo6Hv+KOh7/ijoe/4" +
        "o6Hv+KOh7/t0YexdtTIP/dVyL/31sk/+JfJ//kYyn/5mcr/+lrLv/rbzD/7XMy/+92NcT/VVUDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAizccLoo5HrKKOh7+ijoe/4o6Hv+KOh7/ijoe7s9NHeTbVCD/3lgj/+BcJf/iYCf/5W" +
        "Qq/+doLP/pbC7/7HAx/+50M//wdzV4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACLOh0sizoeooo6HvuKOh7/ijoe/5A9Hs3aUR/+3FUh/95ZI//hXSb/42Eo/+VlKv/oaS3/6m0v/+xxMf/vdTT68Xg1NQAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAIc4ICCJOh6Rijoe9Yo6Hv+rQh3A2lIf/91WIv/fWiT/4V4m/+RiKf/mZiv/6Got/+tuMP/tcjL/8Hc01v9xOQkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhj0YFYk6HoCKOh7o" +
        "yUsf2dtTIP/dVyL/4Fwl/+JgJ//kZCn/52gs/+lsLv/rcDD/7nQz/+95NJIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIMyIPokAgaNpRH/fcVSH/3lkj/+FdJv/jYSj/5WUq/+dpLP/q" +
        "bS//7HEx/+51M/7xeTdKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhOHHbaUh//3VYi/99aJP/hXib/5GIp/+ZmK//oai3/6m4v/+1yMv/vdjTl8nk2EwAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAP+AAALZTx6+21Mg/91XIv/gWyX/4l8n/+RjKf/lZiz/2mMs/+ZsMP/uczP/8Hc1rgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADbUhsc2lAe7txUIf" +
        "/eWCP/4Fwl/9BYJv+bSiz/rGdL/5tOMf/HXi7/7nQz//J5Nl8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E4cXNpRH//cVSH/3lkk/5pKLP/t18P//vLg//jq1v+eVDb/4Gsw/+" +
        "92NPPxeDkkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANdPHafbUyD/0VMh/6lkSP/+8uD//vLg//7y4P/HmYL/xloq/+1zMv/vdjXE/1VVAwAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAN9QIBDYUB3h2FMg/5lLLf/25tP//vLg//7x3/+qZ0v/0mAq/+xwMf/udDP/8Hg1eQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZTB5D2lEf/cFPI/+eUTT/xJN8" +
        "/6hhRv+xUy3/6Gkt/+ptL//scTH/73U0+vN6NCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E4dj9pSH//SUyH/wE4i/9BXJP/kYin/5mYr/+hqLf/rbjD/7XIy/+91Nb0AAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20kkB9lPH9HbUyD/3Vci/+BcJf/iYCf/5GQp/+doLP/pbC7/63Aw/+50M//veTVSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAANlMGy/aUR/43FUh/95ZI//gXSX/42Eo/+VlKv/naSz/6m0v/+xxMf/udTPUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYThx12lIf/91WIv/fWiT/4V4m/+RiKf/mZi" +
        "v/6Got/+puL//tcjL/73g0MQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/gAAC2U8etdtTIP/dVyL/4Fsl/+JfJ//kYyn/52cs/+lrLv/rbzD/73QzjQAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3VUiD9lQHtbcVCH/3lgj/+BcJf/jYCj/5WQq/+doLP/qbC//7HEx1QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANVOHCTa" +
        "UR/r3FUh/99aJP/hXib/42Io/+ZmK//oai3/6m4v/P+AKwYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADbUB0j21Mg1d1XIv/fWyT/4l8n/+RjKf/mZyv/6Wsu/+1y" +
        "LB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA20kkDttUILHeWCP/4Fwl/+JgJ//lZCr/52gs/+pqKyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdVCJS3lkj0eFdJv/jYSj/5WUq/+xoLxsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAd" +
        "5cJj3hXSeR5GIoyv9VVQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////w" +
        "AA////////AAD///////8AAP///////wAA////////AAD///////8AAP///////wAA////////AAD///////8AAP///+f//wAA////g///AAD/4f8B//8AAP/g/AD//wAA/+A4AP//AAD/4AAA//8A" +
        "AP/gAAD//wAA/+AAAf//AAD/8AAH//8AAP/wAA///wAA//AAP///AAD/wAB///8AAP8AAH///wAA/wAAP///AAD/AAA///8AAP/AAB///wAA//AAD///AAD//AAP//8AAP//AAf//wAA///AA///AA" +
        "D//8AD//8AAP//4AH//wAA///wAP//AAD///gAf/8AAP//+AB//wAA///8AD//AAD///4AP/8AAP///gAf/wAA////AB//AAD///+AD/8AAP///4AP/wAA////wA//AAD////gB/8AAP////AH/wAA" +
        "////+Af/AAD////+B/8AAP////8H/wAA////////AAD///////8AACgAAABAAAAAgAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv0AgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAK/UCZsu0sj6LZGIfuxQh+aqlUAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAADOA5go6lfowM5n/BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMxeKx7JWSi+xFMm/79OJP+5SiL/tEUg/7A/HpEA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9lfvKPZr7/z6e++s+ovt8QJ//CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANVj" +
        "LVXRYCztzFsq/8dWKP/CUib/vU0k/7hIIv+zRCD+sEEfSgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGov8LPZz7/z6g+/8/pfv/P6r8/z+u+9VBtPozAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAA3XczD+BtMqLaaC//1WMt/9BeK//LWin/xlUn/8FQJf+8TCP/tkch/7FDH+auQxsTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK6r/Bj6i+/0/p/z/" +
        "QKz8/0Cw/P9Btfz/Qrn8+kO+/XoA//8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Hg2Qud0NeLicDP/3Wsx/9hmL//TYi3/zl0r/8lYKf/EVCf/v08l/7pKIv+1RiD/sEEeqAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/qfzbQK78/2jH/f+u7v7/hdv9/0nE/P9Dxfz/RMj8qDnG/wkAAAAAAAAAAAAAAAD/gEAI9IA8jfB8Of3reDb/5nM0/+FuMv/cajD/12Uu/9JgLP/NXCr/yF" +
        "co/8NSJv++TiT/uEki/7NEIP6yPh8hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQLH8nEG0/P+F2/3/w/n+/8P5/v+19P7/aNj9/0XQ/f9F1P3PRtz/HQAAAAD0ejcu83040vWBOv/zgD" +
        "r/7ns4/+l2Nv/kcjT/320y/9poMP/VZC7/0F8s/8taKf/GVSf/wVEl/7xMI/+3RyH8sEYjHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEG1/FpCu/z/etj9/8P5/v/D+f7/w/n+/8L5/v" +
        "+C5/7/R9v9/Uvf+XfvdjNz8Hg1+PJ7N//0fjn/9oE7//J+Of/tejf/6HU1/+NwM//eazH/2Wcv/9RiLf/PXSv/ylkp/8VUJ//ATyX6u0wjZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAABAv/8YQ8H8/F7R/f/D+f7/w/n+/8P5/v/D+f7/tvb9/JfJx3HsbzK+7XMy/+92NP/xeTb/83w4//R/Of/1gTv/8H05/+t4N//mczX/4W8z/9xqMP/XZS7/0mEs/81cKv/IVyjXw1UoMwAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAETI/LlGzv3/uPb+/8P5/v/D+f7/ovH94tKEWmzpay7t624w/+xxMf/udDP/8Hc1//F6Nv/zfTj/9YA6//SAOv/vezj/6nc2/+Vy" +
        "NP/gbTL/22kw/9ZkLv7QXyuZ0V0uCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFzfxcRdP9/4/r/f+99/7+m+XrqORjKaLmZiv/6Gkt/+lsLv/rbzD/7XIy" +
        "/+91NP/weDX/8ns3//R+Of/1gTr/8n86/+16N//odTX/43Ez/95sMejaaC9MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARtH/C0ba/fJf5P3O" +
        "vJd7buFeJuLjYSj/5WQq/+ZnK//oai3/6m0v/+xwMf/tczL/73Y0//F5Nv/zfDj/9H85//aCO//xfTn/7Hk3/+d0Na3mczMUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABT1uxE2Vckgd5ZI/3gXCX/4l8n/+NiKP/lZSr/52gs/+lrLv/qbi//7HEx/+50M//wdzX/8Xo2//N9OP/1gDr/9IE68vB9N2YAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACVPh862VEe0ttUIP/dVyL/31ok/+BdJf/iYCf/5GMp/+ZmK//naSz/6Wwu/+tvMP/tcjL/7nUz//B4Nf/yez" +
        "f/9X46w/eDPiEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEAgCIo5Hl6KOh7Pijoe/7JEHcPaUR//3FQh/91XIv/fWiT/4V0m/+NhKP" +
        "/kZCn/5mcr/+hqLf/qbS//63Aw/+1zMv/vdjT/8Xk2ov9VVQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFNyEXizkdk4o6HvCKOh7/ijoe/4" +
        "o6Hv+KOh7yzkse49pSH//cVSH/3lgj/+BbJf/hXib/42Eo/+VkKv/nZyz/6Got/+ptL//scTH/7nQz/+93Nen0ejcXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAACAKysGijoe2oo6Hv+KOh7/ijoe/4o6Hv+KOh7/ijoe/487H9DYUB7821Mg/91WIv/eWSP/4Fwl/+JfJ//kYin/5WUq/+doLP/pay7/624w/+xxMf/udDP/8Xc2sAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEAgCIo6HuOKOh7/ijoe/4o6Hv+KOh7/ijoe/4o6Hv+KOh7/p0EdwNpRH//cVCH/3Vci/99aJP/hXSb/42Ao/+RjKf/mZiv/6Gkt" +
        "/+lsLv/rbzD/7XIy/+91NP/veTVhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGPRgViTofhIo6Hu+KOh7/ijoe/4o6Hv+KOh7/ijoe/4o6HvnISx7U" +
        "2lIf/9xVIf/eWCP/4Fsl/+FeJv/jYSj/5WQq/+dnLP/oai3/6m0v/+xwMf/tczL/73Y09PF8NyUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA" +
        "QBUMijkeb4o6HuSKOh7/ijoe/4o6Hv+KOh7/jTse3ddPHvbbUyD/3VYi/95ZI//gXCX/4l8n/+RiKf/lZSr/52gs/+lrLv/rbjD/7HEx/+50M//vdzXF/1VVAwAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAKysGijkeXoo6HtiKOh7/ijoe/4o6Hv+eQB/A2lEf/9tUIP/dVyL/31ok/+FdJv/iYCf/5GMp/+ZmK//oaS3/6Wwu/+tvMP/tcj" +
        "L/73U0//B4NnsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAACizweTYo6HsqKOh7/ijoe/rxIHsvaUh//3FUh/95YI/" +
        "/fWyT/4V4m/+NhKP/lZCr/5mcr/+hqLf/qbS//7HAx/+1zMv/vdjT78Xs0NgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAiDwePIo6HrOKOh7o000e7dtTIP/cViH/3lkj/+BcJf/iXyf/42Io/+VlKv/naCz/6Wsu/+puL//scTH/7nQz//B3NtvqgEAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiDwePKVCHZPZUR7/21Qg/91XIv/fWiT/4F0l/+JgJ//kYyn/5mYr/+dpLP/pbC7/628w/+1yMv/udTP/8Hg1lQAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E8cotpRH//cVCH/3Vci/99aJP/hXSb/42Eo" +
        "/+RkKf/mZyv/6Got/+ptL//rcDD/7XMy/+92NP7xejZLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAN1VIg/ZTx7f2lIf/9xVIf/eWCP/4Fsl/+FeJv/jYSj/5WQq/+dnLP/oai3/6m0v/+xxMf/udDP/73c16fR6NxcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E4eO9lQHvzbUyD/3VYi/95ZI//gXCX/4l8n/+RiKf/lZSr/32Qr/9RgK//iaS7/7HEx/+50M//xdzawAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYTxyI2lEf/9xUIf/dVyL/31ok/+FdJv/iXyj/r04n/409IP+URy" +
        "r/jDwg/61RKf/qcDH/73U0/+94NGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzGYzBdlQHs" +
        "raUh//3FUh/95YI//gWyX/rkwm/59XO//s1sP//vLg//Hdyv+hW0D/sFEp/+1zMv/vdjT08Xw3JQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADaUR8p2VAe9ttTIP/dViL/1lYj/408IP/t2MT//vLg//7y4P/+8uD/7dfD/4w8IP/kbDD/7nQz/+93NcX/VVUDAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhPHm7aUR//21Qg/85RIf+RQib//vLg//7y4P/+8uD//vLg//7y4P+QQib/2mUt/+1y" +
        "Mv/vdTT/8Xc1fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAB2E4dttpSH//WUyD/jDwf" +
        "/+nRvf/+8uD//vLg//7y4P/q07//jj0h/+NpLf/scDH/7XMy/+92NPvxeTg3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAANhOHRrZUB7s21Mg/7BKI/+ZTjP/6dG9//7y4P/mzLf/mlA1/7RRKf/pay7/6m4v/+xxMf/udDP/8Hc12OaAMwoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2U8cUdlRHv/bVCD/sUoj/409If+OPiL/jj4i/7ZPJv/lZSv/52ks/+lsLv/rbzD/7XIy/+51M//wdzWLAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZTh2g2lEf/9xUIf/ZVSL/0VUj/91bJv/jYS" +
        "j/5GQp/+ZnK//oai3/6m0v/+twMP/tczL/73Y0++94NDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAA20kkDtlPHt/aUh//3FUh/95YI//gWyX/4V4m/+NhKP/lZCr/52cs/+hqLf/qbS//7HEx/+50M//vdzS6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZTx092VAe/NtTIP/dViL/3lkj/+BcJf/iXyf/5GIp/+VlKv/naCz/6Wsu/+tuMP/scTH/7nQz/+91NT8AAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANdNHIfaUR//3FQh/91XIv/fWiT/4V0m/+NgKP/kYyn/5mYr/+hp" +
        "Lf/pbC7/628w/+1yMv/vdTSsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADVVSsG2FAe" +
        "zdpSH//cVSH/3lgj/+BbJf/hXib/42Eo/+VkKv/nZyz/6Got/+ptL//scDH/7XMy+/R6NxcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANpRHynZUB7021Mg/91WIv/eWSP/4Fwl/+JfJ//kYin/5WUq/+doLP/pay7/624w/+xxMf/tczNkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2E4cXNpRH//bVCD/3Vci/99aJP/hXSb/4mAn/+RjKf/mZiv/6Gkt/+lsLv/rbzD/7X" +
        "EyrQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYTx2L2lIf/9xVIf/eWC" +
        "P/31sk/+FeJv/jYSj/5WQq/+ZnK//oai3/6m0v/+xwMeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAA/wAAAdlQHqDbUyD/3FYh/95ZI//gXCX/4l8n/+NiKP/lZSr/52gs/+lrLv/qbi//63YnDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAB2VEfjdtUIP/dVyL/31ok/+BdJf/iYCf/5GMp/+ZmK//naSz/6Wwu/+ltMyMAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZUB9s3FQh+N1XIv/fWiT/4V0m/+Nh" +
        "KP/kZCn/5mcr/+hqLf/rbi0zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAANpQIDDcVSHK3lgj/+BbJf/hXib/42Eo/+VkKv/nZyz/6WksLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAtxVI2DeWSPW4Fwl/+JfJ//kYin/5WUq/+lpLSIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAuBZI0LhXSaZ42An4uRjKf3VVSsGAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAADgZikZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////////////////////////////////////////////////////////////////////////////////////////" +
        "////////////////////////////////////v/////////wP/////+P/+A//////4P/wB//////Af8AD/////8AfgAP/////4A4AAf/////gBAAB/////+AAAAP/////4AAAB//////wAAAP//////" +
        "AAAD//////8AAAf//////4AAH///////AAA///////gAAH//////4AAAf//////AAAB//////8AAAD//////4AAAH//////4AAAP//////4AAA///////4AAB///////8AAD///////8AAP///////" +
        "8AAf///////wAA////////gAD////////AAH///////8AAP///////4AAf///////wAB////////AAD///////+AAH///////8AAf///////4AA////////gAD////////AAH///////+AAf//////" +
        "/4AA////////wAD////////gAP////////AA////////8AB////////4AH////////4Af////////wB/////////gH/////////gf/////////7///////////////////////+JUE5HDQoaCgAAAA" +
        "1JSERSAAAAgAAAAIAIBgAAAMM+YcsAABC9SURBVHic7Z15dBRVvse/v1vd6c6+sAkkYRWi0QFEQBYhA8oyEhYxgBuDuMwbn/pGmBllztGJ4wxLZBadEZTncxlxjsrMeQd5Dk+UF5wBBcMWMYZFQRF5" +
        "TzaF7Om69/f+6CydpLfQ3anu5H7O6dOVulXV9avf7/7uvd+6VQE0Go1Go9FoNBpNxzBk0Vd9c+/+arrV52Gz+gS6CgMLPk+1OWyzSdA0EjQeAv0UUQ3AiQCxVedFVv1wVyC3oCyuzhY/ByRuFQZNB8" +
        "FJgkBEaPwWsF32yQu9vrHqHHUGiAC5BWVJNSLh7jqBZRDIIgJAcDve8yMICtwfgA6AzsDgGUcdMsn4aY3gZSQ4Ha1qe+M3BNy5lwACZwHYbdU56wAIE/0KPpssCX8i4iuaHO7xaXR460wAEk4rz1sH" +
        "QIj0nVveLc5mex7AvGCd3qJccJyV568DIASybj48yiDxBkAD2uV0j3LBZLfSBmHlj8cuTP3mHvmZIPEBEQ1or9M9P0zW+kBngPZSwEZ/eXQtA/f57N0HcLpnmQCdtdIcHQDtILegLK7CdXQDCxSE4v" +
        "SWQ0HrhoCADoCg6ZO/J6HCZdtMhMkhO92jnEicsdIu3QcIhrxim00kv0lEk0N2eqMGIAAiYrukr600TQdAQJiy0vo+D8JN7XK6h/jT6HAv+x7b/cduF620TgdAADJnH15J4CU+nS7gXe0LbmRwwErb" +
        "AN0H8Et2/qH5AD3itSa3Q+3zWS6wz0r7AJ0BfNJ3bvkQCHqhhW7fzp5/wHLmD620EdAB4JX+ecedpPA6CMnhdrpH2Xeo7L7DSjsBHQBeUSm1zwgSIyLgdM/1f9+7nlxW2gnoPkAbsvIPzQbRvRFyet" +
        "OHid+y0s5GdAbwYMCsg71YYH2knO5RfrEuUb5toalN6AzggQtxLwhCzwg5vXnkYNArZYU9K620tREdAA1kzTr0YyLMDMnprWf8tNYIGj9Qz1tpqydk9QlEA33nlg8xlNgHQmJrQcfTqU1/e9mmRQ33" +
        "X168pyh9stU2N6L7AHnFNiHxZxAS29T0ADX5kjqJoN9YaW5runwAZKX0fpyEGONZU33o9qELP0TvlhSlbbPS3tZ06T5AVv7hUUR4NESnBlvOStBjFprrlS6bAXoUlCVB4C8g2CPo9KZyQfS3vStTLZ" +
        "v+7YsumwGcdcYfSGCwN6exeRGQ1W7n2ZNAzrRQg+IisXzYUoN90CUDICv/0GwiuruF04mBquOQFUcAs7rF9mRPhD0jB/b0IT4d7ne4CDy6u6jbyQ42Myi63DBw0NzPetYr+TERejX16uGCOr8LXNc8" +
        "P9OwCRARTJdsXpfQE86siRBxzmCGe41Dxl0lztTxKCRlhb2B6GIZgKlOHnpRCNGreVjGTc4nAmbceDVumT0Cgwb2BAAcO34aGzftx5atByGrT6P2q/eROGgqiETLmt56noD7u0aRuCtanQ90sQzgVv" +
        "torae4w1Wfgy98DCJg+bIZmH5Drtd939lWhhVrtoAZcPYeCcdluT6zQLOGIB7csyr1Tx1rZfvoMqOArDlHBxFRUYs2GwBXHgEA5P9gmE/nA8C0KbmYM3MEAKDuTFlgiVjQu3tWpTwbabtCpWsEQF6x" +
        "Dcp8DYQkT90e5neArAUALJx3bcDDzL95JACAzVpw9Tl/Pf+ziuw/hIUvfgiWLhEAWSm9f9lG7SMA0n1DLjUlHpl90gMep2/vNKSlxAMAZP1F38NB4F/3rkj834gZFEY6fQD0nVk+loiWe6upjV0gEs" +
        "F3hYSt4ZIxvKd/4KWS1WlvhtWICNKpA6DX1NJEYaNXQDC81VSyJwAALlyoxpmzgW/PnztfhW+/rQIA2JzJ3tL/cREvfxI5i8JPpw6AOKfjGQJd7qujJhzdAGEDM7Dp76UBj7fp7VIwA2TYYUvu2Tqg" +
        "FATftbvQ2gc92kunDYAGtW+JX4lWGLClDAEA/GXjR9hfesLn8Q58/BVee9Mt5Tt7XgESRouAIoFVJSvT34+8ZeGlU+oAXtU+XxM8IFF3ciu4vgJ2u4HFt4/FnJnDkZzkfnNLZVUd/nPzfrz82odwuS" +
        "SEMxVpufkQcQ7P4+2rjk8dW1ZI9Rab3m46YQAwZc468pYQDdO7gpi1A7MKdV9vh6qvAADYDIE+fdIAAKdOfQdTuoU8w5mC5JxpsMWneB6jlg1j1J4VyZ9YZXEodLoAyMo/fD8JPOt1KpefTACYcJ09" +
        "CNf5owDLFsckYcDRYygSMq+BsDtaqn0QD+xZnRr1go8vOlUAZM4qGyzIth+EJL8O9zN3j9kFVX0aqr4SRATDmQR7ah8II65tFjHo3ZKVqdNiQfDxRee5GZRXbCOIDa3VvmZdHs3ZwI+EK0QcjNQs7/" +
        "vHqNrnj04TAG61j9qqfWGa0dP2g/tjRe3zR6doAvrNLh/HEP+AaBB8gpnaHUo50Uslq9OWWG13OIh5HaDX1NJERfSyL7UvApkg5tQ+f8R8AARS+8IcFDGp9vkjZvsAmWOe+p5IyroDgdS+MARF87xB" +
        "rNwTg2qfP2IuALKvKxoPgUeZMIYTckARdrpHu7+v2pn6KwtNjwgxEwDZE1ZNgBKPAJgJgJE0fA8Z8aPC5nT/7wCqZcP4YSxKvYGI8gAoFNkTEm+C4segMKpptS3jn+TMnnhJTvf37n4f+zLop7Eq9Q" +
        "YiKoeBubmFcRUpCQtB+AWAoZ5lROJLzpjeHYbd+5O8QQzpfN0T8FYOQVv3rEqdHuuCjy+iKgP0yCtMiq9LuLuC8DMAfb1sYqrk6yrJsPfz5biAbXr7moazStgXd1bnA1ESAH3y1nS31csHUE8PgpDh" +
        "azt2ZO0gZ4+8dnfkurja5w9LA2DghFXZpqJlqFf3AJTgd2NhP0gpI66PtNOby/DiR6vSNkb6GliNJQGQNa5oEIEfMhX9CIAj4A6MKk69PpmIjEg63VPtI2d0PswZbjo0APqN/e0IJvUwwLcBZAS7Hy" +
        "cO3U/25AkRdnrjp9Opff7okABoHMMz5Mz27ksiYTcScyZE2OmdWu3zRwQDgKnfuKduZuBRKAR+7MYbRKdl+sSBIlJObztPoFOqff6IWAD0G7fmPxi4K4RDMCeN+EIYjtEhOz24d/fXAsaizqj2+SMi" +
        "dwMHTFg1jMGhOB+wd/snObNGt8vp3h/RDjJgaFnJ6uSyUG2PNSISAGzyBQAy4Ia+IHEMqddd60+395HCLylLgGhryaqUdSEbHoNEJAC+2LX8CyJeDuBSFDQXp1xXA2FL6Ci1jzu52uePiE0I+XLnI0" +
        "+BsZiAdv1XLHZkfkCOHrnt7b1rte/SiOiMoBMf/vzPSReqM8GYD8J7gc/GfpBSrgk45NNqX/igjvyx/mPX5CiSPwbEEoCTWhQyV6v0yedEXEpWqHfwgisXp+K4PmdnUY+KjrwG0UaHBkAjg8c8k1Jv" +
        "1C4E8ACAqwGAE4buoCS34BP2Wby+AsKgVxPsdfdvj5JXt1uBJQHQDFO/8UV5ykifT+mT/iUyNd1HQDSXfS5g3PnBkwmW/wMnK7A4AJrJnnuogEg8R0QZYa3pwewrSBKJNRc4/vGuJgRFTQAwgwbP+S" +
        "yT4/AKiL4fdE0PY5ZgpUrIVHfu/HXKYauvR0cRNQEgj01bBqIhZy72WDpuReE9RLSaBDk8U3bQ6f1SysFQSoKlqmEll+9ekfFMV9AGoicAjtxYBkNcCYFPhYhfdPmjT9eS4A0QGB6J/kDrcpYSrBRY" +
        "ycbld1yoW7K/KPuU1dcmkkTFk0FcPmUsJF0JkwHJV6qUqR8dWvfOs/fML51IRKuJSIVbA/AsZ6XArBoCQIGZwUpNM0zjwLUPn5ht5bWJNFGRAWTp1PUw+F4IAmx2UNZSQMSB609XCPPz/Jyl8w2Q8b" +
        "IgCrtGwGBvtb9hueGb1av1sub+srW5nW64aHkG4OI8J6RaABOAZJDjckDEAQAormcyO0cWf/r7/77NZau/Wgi8GtZMAAaUAli5v5UCuGGd4oaswGCp7rQp+8Fh9x2eYNV1ihSWZwBz1w3zYOCvJAAI" +
        "ArIXgJKGttmO6788KeSpvNyf33mNEHiOBGWEmglYqYYaLz2WW9X+lutNVvxbVUGPl23M7RTDRcszACQWwHS/locRB0oc7HUziuuXyY6rDx9csWEwhBpOJIoD1fSWt3y9OL+p7WfPtt/9t/f1NlbyET" +
        "jrd+Qs2j2k4y5S5LA0A/Dm/ASZWn0aAokQAGXkgAYsDLQXUHesvKrq4qTxv1l4mzBoNRE5Wgk7/rMA0KL2q+Bqf+v1NUqp5YffGBPTw0VLM4B0Vs6A5ERIuKePxGcGsRcBjkFXJMSL8tKli4pZiJEw" +
        "6ICviSHeskTr2t+67Xf3CdqubzlSUPFQ6g+Xz9uxZeisHX0ieZ0iibVNAOOmxs4fJAOJ2cHtVrEPOPd2NwXes++h2wtGDTk+nkj8jog4UCewZUpvPfzzv+wtUEjxNEXm/kH522ZE8lJFCssCgBkEE9" +
        "MhGTABKAFK9PY4oOdOEvhmE3D6bcAlAcl2KP7l2mm/WLh3TfoyAt0IwkmfPX/2qMXsEQiB2/4AwSF7Qqn/GjR9y+KOuHbhxLIAcL01cThM9HanfwYoERB+nhVxXQB/8RL4fGlzxjAhIdVPbP23vggA" +
        "JUVp2xzA90jgdW+ZoLkWew772q7z7Wy/gSIUY93AGzYHl8aiBMsCwHCJ8W4nsrv99/lvlRh8Zi9U+TpwxddoyhgSVazUPGPIu097br1jVdq3u3+deisE3QHCd23VPj+1viEreO8TBBUoTsnIj/S1Cy" +
        "fWNQEmj27q/JkM1FQC9S3/Xx9qzoHLXgEf3wzU16JpuCj5a+GiSbbc9zb5Ov6uXyW9ZpAxjARtv9Q23x0Qvmu/t0BhJYN+5C0asOzpYFYYSSYDBgAmgCX44F+B/mMBsxY4+yn4fLl7hNW0DQPMOw2b" +
        "uoVGb/+/QL+xozD+BAp5ynhVsYxZPQnFDp9qn98U7y0gvAcPRBBzH6MIS3QAZpC5YWIVBMWTgNvBDZM3AiyvN7pnPEi5G9utwo1+7NthwpQblJRXtXO879YJgtne5DdPvD97QTivVaSxpgl4dVwPSM" +
        "RDsvvF3E1DQV/LXAlJi22Ttv3oUpwPAB89mV7qdFSMYoXVrJRqT4/fW/vfdpnPCKr7t/BdpI7Bmgywbmxf0247CaOhdjfcByCjeRkNyyRonxDiVrpp25Fw/f6IpSenCFO+rJTMDPIeQMD1YHXLl8Vz" +
        "/xauc+worMkAIrGyqfPX2BGUDDabl2GijhQKRU33seF0PgDs/13mNtSaV7HiDQHUvuCWmf89Fp0PWHgvwLX2+k8gkNumrRcAGfQ/huAHaOE/yiN9HsPvO1SglHqOlcy4tD6BOhZfj+GHd86OyecLLB" +
        "sGkuQnIJk92noJye+BOc922/tTOsL5AHBgfc5GKXgEsyoOtsZ7tP2mYPP2WHU+YPHdwLqnx11FNmOsEKgwbHHFdO+2b6w7G6Yr7tj7EBSvZikdQbb9T5zYPrfQunMOHcsnhEQbuQt2D5MsN7BUVwW4" +
        "VfzBCU6dhO3fN60+51CwfkJIlFH2xpjS2oS6UQz1e1asvN4BZD4quH5erDsf0BnALwPz3xtFrJ5gydNYScFSuViZr7uUsfTU9vyzVp9fONABEAS5ecVJtY66y0io059t+UGXeH2cRqPRaDQajUaj0W" +
        "g0Go1Go9FoNBqNRqPRaDQajUaj0Wg0Go1Go9FoNBqNJsr5fzI7+Gu3YtAGAAAAAElFTkSuQmCCiVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAlb0lEQVR4nO2deZwU1bXHf+dW9+zM" +
        "DAMoyzAMm7ggoIjKJigxRg2IGDBuaCTBJCYakyh+kk9eRhOVRZ/Rl/iUJC+aoHmRJL6X5MVEkQxGRRgGRYUBhsUBjMgmIwKzdN3z/pjpnq7u6r16P9/PZz5Q1fdU3boz53fPqXuqGhAEQRAEQRAEQR" +
        "AEQRAEQRAEQRAEQRAEQRAEQRAEQRAEIQuhdHdAEFLF9Dp2fbhr35kweLwiGg8iavpl9e3p7lc6EQEQcpc6ViN2tIxzGepiEF0MwkUAehFR118+4aOmX1T3T3c304kIgJBTjPhmc6FqLZhKjJlM+AIR" +
        "DQQBBJ/Tg6jrz56I0KbaKnctH96a3l6nD1e6OyAICVPHavj2lmlK0c34mOeA0Iv9HB1Aj/Ojx/lBQDGXnAagIS39zgBEAISsZciN7w9wa74Nze/fQkRDAPY5tg//Gd8vCvD7eChEAAQhexh+/Y7x0G" +
        "ohaZ4PoMjWsbuFwDvj+3/ubU9EAPOAFHc/oxABELKG4dftuIShfgjGRb7wPpRjewkR+nu3WZEIgCBkMsPn7biYie4D01QCepzexrF92IT+tsKgIAIgCJnI0Lm7RhHxMibM9O2MlNMHzPB+S35We28b" +
        "jT6puZrMRARAyDhqZ++uJJd5H0h/DSA3EENOH7DkF0V6UJaq68pERACEjGLoNc0zocwnAFSHDd3JOsNHk/f7f+5nX5rUC8pwRACEjKB67rZBLlZPADQLiCJ0RwTHjnZlANQrmdeV6YgACGlnyDXbry" +
        "GmpwjUJ1LontCSn88Afu3ZndSLy3BEAIS0MWrW1l7tbvUwQAsBRFyyi3fJz//zQCFRRDp5V5j5iAAIaaH6qqaz2w31B4BGRr1k51Do72/PDE7SJWYFKt0dEPKP2jnbrjUMYy2o2/mdzOljTR1UfguA" +
        "RABC6pjLxhBP82IGvkPdnul8Th+Dfde+E8m52OxABEBICbW37C5C6/ZnmGheMnP6aJYMA8TmqIOXmXWIAAhJZ9DVTX241fO/AE0GkLycngLso4gCGNSajGvOFkQAhKQyZObWocy0CsTDHMvpKcA+gS" +
        "hCgUUABCEZDLq66TRmeoWIquPK6Z2q9gsnNoQPnbzmbEMEQEgKQ67efgYzryKigb6doZw2TOie7JUBJtrr6IVnGSIAguPUzGw+i1nXA+gLIObQPaUrAxr7nL7+bEIEQHCU6lmbR0DplwH0jSV0T/nK" +
        "QLeRoTivIwApBBIcY9Cc5mpFrpcADEjUMZ2s9gtjz58WoNmJa89WJAIQHGHQ1U19DFOvAmGoA44Z0t6x1KFrX8u2pX2POTQEWYlEAELCnDV3cwExPQ/CKCDNOX2gPQXYW/pEWxwdiCxEBEBIEKZP2l" +
        "1PK6ZLgDTm9OGr/WzPwcTvOTQIWYsIgJAQg2dtu58I16Usp6cA+8TSg7z9PgAvIgBC3AyeuW02EX0/KTk9BdgnGEXY2WvNa50Yh2xGBECIi4Gzto6C4mfQ7Vpxh/6pqPazt9+z6dG+HyQ4DFmPCIAQ" +
        "M8Pm7qwwgD8RqDxqpw0TuqdpZSDvZ39ABECIg872jieJ6DRbp40ydE/rygAAZrzkzGhkNyIAQkzUXNV0G4i+6HOsLKj2s7N3AS8nMg65AkVuIghd1FzVfCbDbCBQif+MDwQLQZAw2EQI0djbtXfAfn" +
        "PjI1WjUzRsGY1EAEJU1E7fXcRs/rfX+cOF7hlT7Rdo392GCH91YEhyAhEAISo85e2LQTg7I3N6CrCPsLJArFc6MCQ5gaQAQkRqrtr+GYZ+iUBkF4onI/S3tXcmPdjb+HDvIQDl9duAvUgEIISldvbu" +
        "Smb9S4vzewkxY/t/nspqv8DP7c4Bwu/E+XsQARDCYprtTxJRTVJy+oAoIp70IFyf7IVB/TaB4cg5RACEkNTM3HYTFK71bmdhtV+g/TuNyyo3xjkcOYkIgGDLoDnN1Uz8WEyzcZjQPTNWBvjniY1K7i" +
        "ECIARTx0p5zBVE1NvWaaMM3dNd7We1V23uTuO5RIcm1xABEIKoadx2NwjTfI6VpdV+FnvFz619tOJI3IOSo4gACBYGX7llNCvUpcwxE8vpo7ZXwONxDklOIwIg+BhxeXMhDPUcgYqS7ZhJSx0owL7r" +
        "Z9X6Jb03JTo+uYgIgOCj3W1mbrVfoH0MKwsK6icJDEtOQ5GbCPlANlb7hTumn/1bG5ZUjocU/9giEYDgrfb7r2yr9osmigBwnzh/aEQABG+13+BEHDumnDywjd85YxWbCPZvbVhS+af4Ryb3kS8GyX" +
        "OqZ229EZRT1X4+e2auk9k/PBS5iZCrDJrTXK085jvegp+ocnqbfQ68oCOikMRh/2rDksppKRvMLEVSgHyljpXqNH+TW9V+PnsG0XcTGp88QQQgT6lp3HY3FKaHmrG7dsJpx4wYujtjz882LK7I+y/9" +
        "iAYRgDxk0Ozt41jh/lyr9uvePK7B349jWPISEYA8Y8TlzYVK618TqCDZjpm01IEC7P3akML9jUuq9iQ0SHmErALkGW0ucynFWu0HgDs/BrcdBsyTAHeAWYNcxVCuEqiiKqiiPlYDJ1KHmFcWeIt5uP" +
        "JRJ8YpXxAByCO6q/2+GbVjmiegj22HPrkPMNttj2l2/0tGEYxeg+HqPQpU0Cu21IF6Po9Q1BNOrFgpfKNhOXXGOTx5CUVuIuQC1XM3V1G78Q4RDbI4pk1YTfBAt74LfbwFYB3biUjB3Xsk3H3PBhkF" +
        "1tk7IHSPp7Q4pD3w84YllQudGKt8QiKAPIHajCdIdTl/z06b2dTTCvPwm2DP8fhOxBqdR7bB80kLimsuBhVXJX1lgAgtVGTKsl8cyE3APKDmqm3zo3m3H7fth3mgPqLzl5YWorKiJGwb9rTh5Pur4D" +
        "n2ge8cSVoZYDDdtq6uzyfhR0GwQ1KAHGfoFVuGeFxqExFVhA2zPa3QB9eA2RN0jMryYnz+8rG4YEItRp8+EIara97o6PBgx+6D+OfrO/Diqvdw5IiNcJBCybDPwlXSL2LoH0+1ICk8tf6hyq86PW75" +
        "gghALlPHanDjtldI0XTfZG+Xk+s2mAdXA2abxdxQhBu+eCGunzcBJUUFYU91oq0Dz/1uPZ57fj08pvW+gXKXoHTklSB3UfQ5fXT3BHYV6M5xry/td8yJ4cpHRABymJqrtt3L4IciOZY+uhF8/H2LbW" +
        "lpIe7//kxMOLc2pnOub9yNf3vgzzhxosOy31VRg9La6VHf7LPrb8C2RzFNXbe04s2YOihYkHsAOcqQWc3nMPi+SDk1d7aCj7dYbF2Gisv5AeD88UOx5P45vjTBi6d1D3Sb3zs5470n4BMHfkCcP3FE" +
        "AHKQEZc3F2qYz0RT7cfHtgGwPjF7yw0T43J+L2NHV+O2W6YG7T+5/11Hqv1AaDSPVD4QdwcFHyIAOUiby1yKaKr9YILb9ltsT+nXC/OuOS/hPsydPR4DTq2w7PN8shdsdno7FfIGoA//G4I9bY4Tqe" +
        "sbpeDHEUQAcoyaWVsuJYWoqv247SAQcNd/7uxzUVToTrgfhkvh2i+Mt+5kDc/x/Yk+M/Dt9Q+Vb0+4gwIAEYCconb27kqGiv6bfDsOBR1j6uSRjvVn8gUjgvZ5jn0Yvk/hheFvDYsr5Ou9HEQEIIeI" +
        "+d1+5kmLfWVFCQb2r3SsP6eeUo5T+vWy7NOdx237FEW14EGYri9BXvHlKCIAOUK01X5d/+36jM0TlmMEOqsTVFWWWra5sz34zr6v02HEivWChmVl1hsWQsKIAOQAA6/aMZiZfxL7E3hkOY6hrNtOUF" +
        "AQ8LiJ9kRc8rMRq+UNS6r+7HjnBBGArKeOlaE9v6Z43u1nFFoO9XGrNSVwgkOHP7VsU0Fxz/mjE6tdBbpTHvRJEiIAWU7NW9vviffdfipAAA4c/AStnzgnAidPduCjQ9ZndAx3WSxPAHqUphuk1Dd5" +
        "iABkMdFW+3X9N1gYqLCP/+GgNWPDxhbH+rd2/S6YHutzAUZJZc/5I1T7MdGPpdovuYgAZCm103cXRVvtF0oYqLh/0HH/+Oe3HOvjX/7+btC+gt5DLOmJtz82eX8jHyl/0LHOCLaIAGQpuqIjumq/cM" +
        "LgKoIqrLIc993NH+DNhl0J92/dht1B0YS7tB9UYWk0YiXVfilCBCALqZm15VIGf8OJ9/UblWcGHf/BR/6GAwfjT7sPHzmOZY+9HLS/cMBo2z5JtV/6EAHIMmKu9otwT0CVDQQV9rac4+jRE1j0wxdw" +
        "8JD1Dn40HG09gXt+8AccOGi9+ecq64fCPkOl2i/DEAHIMpLxTb7uU84DyLCcZ+euA/jaXc/i7Xf2Rt23zU3/wpe/8Rs07zxg2U8glNacL9V+GQhFbiJkCjWzmm5moqcdfqsOiAie1p3oPGD/bVpTJ4" +
        "3EnJnjMHbMYLgM65xhasZ7Wz7A839sxGtrm8E2rltaOxFFp54R+RVg0LOk4Ce1iABkCbWzm2pNTZuIqDxaxwYChCBCG8+hTeg80hSyDxXlxagd0gen9iuHqTWOtp7E9uaPcOzTtpA2xf1Ho2TI+fJu" +
        "vwxFXgueDdSxMhu3/YpUl/P7CBEF2Do/IqcH7n7jQIW90LG/AXZTeesnJ7Hp3X1RdZlIobj6XBQPHBM59FfY6TY77456PATHEAHIAmo2bl3EoV7s6SXEDcBYVwbcFSNgFJSj/aMN0G1H4+qvKixD2b" +
        "BpcJefajl+yGo/k26Uar/0IClAhjNkVvM5msw3vQU/Mbw0M7b0wG/bGyh4ju5Ex6Et0B3R+aYqKEPxwLEo7DcCREb483fvY6K6DYsr7nNuxIRYkAggg6mdvrvIRHtC1X5d/w0f+nvbB0YI7qqRcFeN" +
        "BLd/jM7WvTDbjoA7j4M7TwKkQK5CKHcxjLL+cFcOhLukL0AUdN/Bcnz/cyhs4MNS7ZdORAAyGF3RsRRIrNov2tA/XOqgiqtQ6P2Kr1ARRph3+4Ws9oO6Qar90ovUAWQoTlb7+dv7fx7HW3ksM3pC7/" +
        "Yj3CXVfumHIjcRUk3Nle/0ZqNgk7fgx5mcnmKzJ6vTxlVfENr+xYbFFVdCCn7SjkQAGQgbBY5X+4W0DyEe/sdwOIo4qJRU+2UKIgAZRs2spptBmOfddiynpwD7GB07nNjEZM96wboHyz6KZ2wE5xEB" +
        "yCCGzNw6lEGPJ5TThwjvLW3gcBQRpT0pPCWlvpmFCECmUMdKE37lLfX1EWPonqqVgZjtpdovIxEByBBqNm5dBMK0kDl5mNA97SsDke09GvJuv0xEBCADGDKr+RwmqkulY4aLEBxLHXxt6EeND1Wsi2" +
        "1UhFQgApBmnHi3X9d/Ewv9E7L32niFyP+YChv0x+UPxT9CQjIRAUgzZnnHMiT4br94Q/+Y7aXaL+eQUuA0UTthaX9dNnQ+E9+ecTk9BdjHGUUQ8C2p9stsRABSTO2FD9Vqpe7ShHlcOlwTiJxw7LhS" +
        "BwqwdzSKoD+tX1zxi/hHSkgFIgAponri4rMVGXdr8HUAXCg9ey0ZpRMTceyoZ2MKsE9JtZ+xML6RElKJCECSqblw6WQo3AvgSoC7vMQof42Lh07xRdpS7SekCRGAJFEzZfEUaLUIwOetn6i9qJwyNl" +
        "er/Zjw5IbFUu2XLYgAOEqdqplSeiU0/wAaE2waaO513hFS7uge9AkRumfUyoC/vcLOssIOqfbLIkQAHOCss+oKjpWXfBGE70HzqFDtqKD/q1zUf7pvO0eq/bo/92jQDfV1p8T+bSJC2hABSIB+0+vK" +
        "ittLFhwjfBdAddjGZGzV5edNiiV0z5Zqv659Uu2XjYgAxMHA6Q/3dXWY30AHfROEqsgWaOPKyS4iI3er/Q5LtV82IgIQA8OmLK7xaPoOOvSXASqJ2rB42Hq4Ki9KimP6DOBM6iDVfnmFCEAUDJ60dD" +
        "iB7/Boug1AYUzGqmgjl42emnE5PQXYxxlFkFT7ZTUiAGEYMvGRc5j0XQBfj8Bvz4wKOsrlUwbkarUfEf2vVPtlNyIANnjX8Bnm5yO3DkPZ6CZy5261HynjtjhHRsgQRAB8dK3hk8nfZ40LEj6cUZHT" +
        "1X5E6lap9st+8l4Axo9/yn2woPU6EO6F5jOYIttERu1F5eScrvZreKj8L/GPj5Ap5K0AnDpmWWlhKX/5ILV+B8BgBw8t1X5C1pB3AjDigsfLO1Tbl6D4XjD6O318qfYTsom8EYChFzxwqmm4vtaBtm" +
        "8BqEAyvpYi16v9iO6Xar/cIucFoGbKQ8Og1Z0maCGAoiSeKh+q/RbHPzxCJpKzAlB9wbIxysB3obtfwJFsioZLtZ+QdeScAPQ8h89XwjrPJg9VtJF7nZW71X6EO6XaLzfJEQFgqpny8OehcS80T0rt" +
        "qXGEK6cNyulqv4cqfhn/AAmZTJYLgPcFHMvqoHFuWrrQ6+xtZBRJtZ+QlWSlAIwf/5T7UEHrQiZ8F5pr09YRo/x1Lh462Rdp51a1H0u1X+6TdQIw4oLHyw8arb8HcGl6e6L2onLKmFyt9oPCk+ul2i" +
        "/nybpvBmp3tT2NtDt/V7UflLtXVE4bInTPqJUBf3uFnScKO+6Jf3iEbCGrBKB64tJpxLg63f2ggv6voqj/WN92Dlb7bZZqv7wgqwSAiKakuw9d1X4TcrfaD3SfVPvlD1klACB9OM09OMmVUwwilZvV" +
        "foS1tbvk3X75RFYJgMvjeQGM42nrQPGwBrgqRibFMX0GcCZ1iKPaT5l088qVZCYyREJ2kVUCsHvd9z9iQnoeRVVFG3L63X6EO9ctq2hOYISELCSrBAAA9r5xz38y8OOUnrSr2m9wblf7VUq1Xx6SdQ" +
        "IAAHvfuOcHRPxNAB0pOWGvMVvJKDo1EceOejamAPvkRxEHpNovf8lKAQCAltcX/ZShpjDhBQCepJ3IKH+di2t9zxfkYLWffJNvHkORm2Q+Q6Y+OoDNjvkA3Q5HX++l9qLP5yq9BT/+Thuuks/i5NG0" +
        "8du2a+/vtIHtE7R/omFx5e3OjZeQbeSEAPiY+7xR82HLFWC+A4wZSOz6NPc6/10qGjA2Kqd11jGjEptE7Imw43hRxzlS8JPf5JYA+DFoyiOnGVrfCvBXgKi+v88CFfSv1xXnTw9yuiQ7ZiSxSdS+u7" +
        "1HK5oiBT9CzgqAl9rpdUW6vWQeCHcBGBeVERlbuc/lw4kMd4odMyn2gfuI8F/rF1cuSHhwhawn5wXAn5opD4+H1gsB3ASgOESzNu590T5y9R6RMsd02j6yWDET/VwXfHpXY93AEw4Ps5BF5JUAeKmd" +
        "/milbu+8GcCdIAz1/4yLh7+KsrMuyoqcPvEooolY3/jmg5UbkzXWQmaTlwLQQ52qubD0Ehi8EIw5UIVvc5/LzrUU/Djg2HbtY7JPbhTRSYoeHNxU9iMpA84/8lwAehg8aelw6j1jEVxlX3HCseNKHd" +
        "IRRfTYv0qmMf+NB4pbkj/aQqYgAhBAzdVb54LpSSKqcjL0t9hn2MqAn/0nRHT3G3Wly5M2wEJGIQJgw7C5O2tM0/M0QV2c0GycwSsDEez/0On23Lb+e+XpfvxaSDIiACFhqr2m+Q4QLSFQYbShe8au" +
        "DAC27UPaM+8HY8HrdaV/TclwC2lBBMAG5ukuonoPAIy4pvksU6kVIB6XEY4Zo324/oZbWWCtATAz8887SJYLc5WsfRgomfD7RX80d3+ujnmuseMPIzdzqZpIoCUAtMXRAJ9zdv03wLH8Pnf8PQBh7P" +
        "0/D+yvv1hZ7P3aMDMABmsmaF7o9pRsuPB7R9PzvQtCUpEIIADedskg7XK3gGCwwhuGUvOp5sWdADD8uh2XgNUzIFRnWk7vWBTB3CUAzGDWgPZu605APzi4ua8sF+YQEgEEoMl1C5gNMEAak7SpN5ot" +
        "n10IADt/O2I1mzyalFoBRDfjhosQErL3m8EdiyIszt/9L7zbcLPGD1uGHvzn+Ls/Gh73AAsZhUQAfjCD9PbPbgfBVwYMIkABRPR76nXmt6nPv+8FgBHX75pLhnoSjKqk5vQpjCKYGdA6QAS6t3V3RN" +
        "C1/xNofXfDIwNluTDLEQHwg5sunaZB9T7nV+gRAVcFcMqXNE5sv9/oc+d9ADBs/s4aF7ueBuFiILTTRXWzLk6xcMze3+F1jwD4OX2gCAAav1cd+qvrf1Yty4VZigiAH+Z7lz4NRTf3zP49P1RxEVAx" +
        "DQAD7buaCIcuovLvHgKYRs3fcweIloBQmOHVfvb2QaG/vwho6+c6aHs/sV6w4fFaWS7MQkQAuuHN08u0dn8IQplv1veLBGjg1wF3nx4D8+N2atv6Jaq657cAcObNLWeZpFYQYVzcUYBN+1TYW2/2RZ" +
        "j17USANUPzz6mj8K7G5bJcmE3ITcBuzA7XddAogwbQtQQOdK2GAQXVVucHAKN3IZec/5zn6PJ65rqCLc8M2dwOz0QmLCGQBqyOCcDqmH6zsO/jUEt2cdoHfm5r332dPTf7Qt0E9PsXQe2IwQu1+2TD" +
        "mNubZbkwi5AIoBvPxktfJ8Kknrzf76fflaCK8aGNOw+00omWmXTKt/8JAGcu2DdDE55WoOpU5/Txh/7ds3qY0D/0zUG/beZOsH5w5OHTZLkwCxABAMAbPlOjCe+j+3U5Fuc3CDT0O4BREuEgHUztW5" +
        "+littvAoBhC3dWFKHwpwR1I4DYHBNJDv2799mE8n4iYOPw2kYAQrRnU6/VynPTe8vP3unU70lwHkkBAGiTrmMNYg1Ac3cK0PVDhbWRnR8AqIC4aMyN+tize7l16chdy4e3bllefROD5oFwJGOr/QJD" +
        "ft9+BOxHQHsEtLceB8QTidXGs2/dvDDKX4OQBkQAAAB8rTf39/5he4WAy86I7VAFNdVcMGarefgn/wYAW5YPWAnGOQDqnczpw0URtm38zgmvk3Y7dc922Dw/wn4E7AeguRzQT5198zsrT5/fFHATRc" +
        "gE8j4F4NcvGW4q2hEU+nc7Dp3+bcBVFs+Rg5YLx3z9ozsYWELU/XRhpNA/nvA+Unpgt+Rnn8sjcmFQ4L2CsGnCfs28oOk358hyYQaR9xGAZroevtC/O/z3pgDF1XE6PwAQUDj8DG2M2MeHl14LEL/z" +
        "RP/HFPF4AG97m4S6Aeg7isMrA12Tvk0oH8sqgN9+60/3Gfy3eyKH/sT8lzNvbHhq/MINUeRUQirIewGAxrUWp/eFrwDKRiR8eHL1KeTS8//bu1y46WcDNn9y/MRE6ioc0kl/ZsDf3uuYAc5rdergUN" +
        "4qAohaHDhQIMAEjYUnjumGM7/YcE7CgyskTF6nAO3/mD7aIONd26U/ItCoW0Glzn3TGHccOKY8O2dS73vWAMCYO/bPUGQ8DUJ1Rlf7JZgmWNv7io46wfzgVt77I6ycJ8uFaSKvIwCl1Rf8b/hZIgFV" +
        "ACoZ5Oj5qOCUXlx07j/Mj//9MQB45/H+rxhFxmgQrXB6ZSDQPmRBj92sD5sbejaRQ2BEEV364OuLm5l/OIoH/XPE7Nfl6cI0kdcCQExX9ji+9w+9a5tKawFKwvBwG+H4xjv0+5c9z3svq2pcUtX69q" +
        "N9b2KieQA+Tl7oH2MoH8cSYWDu3yMOftvB55yoyNx42uw1slyYBvI2BeC/Tu1nutz7QVDBKQCBBl8CGnSRsydt3wc+tBLg495z7WfiW121L70IAOMXHamBB8+AMD05ob9j1X4RioiiSyts2v/eUOZX" +
        "t77wGXm6MEXkbQRgGsYVYFa+G36WFICB0v6Ono+PbwbvXwF4Pu1ZcWD0J6b/M3d/7in+18ySxiVVexp79Z5BhEUE6gCiC/1tUwdvtV9g+B1hdg8X4lv3RTp2YFoRVV3BFzwe9dbwK1eHqbsWnCRvBQ" +
        "AmXd6z/AdL9R80QCUDnDkPM3B4NbD/BcDsDDgPAxoE5oW6vf1N3nXFENSR3rCsaikBF4Cw2XuYjKz2815IGMGI/tjebT0YMF8bfvnfZzvzCxDCkZcCwM/PNaBxqXXpz08IqAAo6JX4iTwngH3Pgg+/" +
        "BrC2CEzwvQe1Fi0nPvCaNizr/XZZceV5AP2EiDgwvA+V93fvtObjSaz2CznrxxBN2JyziIHfDr3i/xzOwYRA8vIeQOf/TJtKhno1eOkPABFQWgU14c7ETnLyQ/C+5wGz1f4cPfcdGIT7jZEv1YU61I" +
        "TvHZ1BUE8Todou7wcC7hMEOm7qqv2Cjx2qfVR90XtPsHHGRy9ddjyxX4YQiryMABTRJbZLf93RAMVd/QcADD68Drzrl0DHUZv7C/CPNk4wY0445weAhgcrXzEKeCwTP5/h1X7W0D5cRBFVXzC4iDtu" +
        "S+CXIUQgLwWANSb2hN8cHJZznAf2fAre9Vvwvr+BTRN2Txf6hf6HlMmfdY166X+iOfTauooj639ccS0T3QSgNYOr/YIFw7I/8NiBfbEeWzHNifO3IURB3gkAMwgmT7A6JFudv7Mt9uMe2Qy9+Wfgo9" +
        "stYuKdEQPOsUV1GhNo9Muvx3qedT8qW+EyXGNAqA+qBQic9WHjoLZOGsnZbY5taY+QDhwxogi6kWg9tmY+PeZfhhA1eScA+N2UkWBU2S79dYfmfOIooKOsTm07DN76LHjHSqDjZPDrxDS67v91Cw1p" +
        "rFZm52Q652/vx3sJr9UV71lLpTNAvAiEjgyu9gsRUUSKQCznLIh3nITI5J0AmKQmInxoDnS0gw/vCH8gz0nwntXQbz8B/rjZ5lhBsz5YYzkVVl5O59QfTfhC6ki/UVe2FKzHg7AJUTletHf77XJ5wG" +
        "6m7nFUv+0oI4HQ+3vOzUBTwmMlhCTvBAAmne9/wy/kTbrtLwOdJ4Pt246Cd74Eve5RcMsawOOxRA+2xwLaofnLrgmrbqOzVnY4eTlv1PV6z62LL2Tmx/y8J8QsDluntg3lw4pDNPu9124jGLZ9sRcH" +
        "sF7j5HgJVvJuGbDz2WmriXBx0NKcouDlusIy0KBxYFcByNMGHN0NPr7fbikv1BIfQPiXZrqmYMqqN5N9bRP/7dMZYP00s1kNZmfe7RdTya9DS4Q97dmj9OkfvDJne7LHLl/JOwHw/OainUw0DNT9rE" +
        "+g8/oEIZr94W2IqFEpzKEpq/ak6vrGLzpS4XbhZ8x8Q3yOF4PDd39nQPwCE+H5AdP89Z41c25O1djlI3mVAnAdFGtU+3LUwJA91LJgyP3ez2Bns0K5jk9NpfMDQOOSqtY3H6i6Eczzmbk19lAeQaG8" +
        "tb3f5yFyf7sUJFSaEPLYzK2KPItSOXb5SF4JAAZP7g9Ggb/zsqUIqGe/3fMBtvs5YL/GcTBudV28+iaatNbmJkJqWPdQ39+YbIxhjXoAAQ6JoPw8vjy/WwQs+xGQywecO6gvwaLRfaxvvF8/b3/qRy" +
        "6/yCsB6CQabHeTrmeZzv+z7j/IGPYT89uG1ue5Zqz+VeqvLpjGJVV7Gpb1uwQa32Jwe5BD+zlqkEDYrc37RAAIOlYocQhzzpBLhJr/uKf+6hXpHLt8Ia8EgEwU24fs3J3PIsRnEfczNJar1rZJdFn9" +
        "1tRfWTiIGx7p/xjIOI/Bm0I7XjR35EOF+AgdUXSpSSzi8IF2sbwcJEXklQAAStmE7JZQ3hIN+ATBbsb37udD0HSV64p/3Ebz0hfyR2LDw/3f61XhuRDgJWDWKa32CxKNkMdm0vyVD16ZIy8ESRF5JQ" +
        "Cs+Wi0N/zYbn9g9GDiBYPdY10zV/85LRcUI/V1Q9saHxtyL8O8DMz7QjlpGqr9vD+Ptay5+sV0j1M+kVcC4FYFH8Ryw88XDVhsGND4AMxzXHPq59BVL/8rLReTAG/9x/BVqpNHM/jZoFnfZqbucVT4" +
        "O2tM6UO4ar9uadii2zu/l8ZhyUvyrg6g8z+n7gW6nqu3rt/bFAL51vW7vjO0+9n9FYbq+BbNW3skPVfgLOMWbp3LwFPM3LvLISOszcfxLsCgtl2pk/92uwF9we5/zNmU7vHIN/IqAgAA8vCfLKG8JR" +
        "LgkDf8WKNemzTJ9cU183PF+QHg7eWnr/TAHMfM9VGszfvtj2IVIETuHxhRkNY/EOdPD3kXAbT9dMppBrAJhKKgWd9vxvd76cYauFSd+6b6+nT1OTUwjVnw3h2ssYRZFwbO1Emr9tP6tT39OqfLl4Ok" +
        "h7wTAADwPDb5Zlb0SxCMEOG/B0QvguhR94I1/0hvb1PLmAWbRutOXsHgsSHC9R4HD3itVxxpQqtB5tjdq69pSfd15yt5KQAA0PEfk88DcCcRTWBCCZE6zMRNIHrFbbj/Ql955aN09zFd1N6yu6hUf1" +
        "zHmu8Gswo760f3br+g3J+ZQaxvbKmf82y6rzefyVsBECJzxvUNn2HgV8RcHc1DQUGzvraJArrba63/uHfN1dek+xrznby7CShET9NzE1YZnZ1jAV7pcLXfPi7q/EpaL04AIBGAECWjrn1jLjQ/Bebe" +
        "scz6NmlCJ2vM2Ltm9j/TfU2CRABClGz73aSVLvA4aF7TM7sHzvoIXe3XvZ8YXxfnzxxEAISo2bxyyp5txoczNPO90NwWU7Ufs2biO1rqZ/8i3dch9CApgBAXI2a/MpxMepzBV0RR7XeYNX91T/3s36" +
        "e734IVEQAhIYbPemkym/gqNH8BzEUBS4IHofGcx33y/n1/n5cz1ZO5hAiA4Ajjx29wH+l76EyCOQKMdvboA7v7nGyUCj9BEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARB" +
        "EARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEARBEBLg/w" +
        "EeDPvKADrVmAAAAABJRU5ErkJggg==";

    // 96 px als PNG für Kopfzeile und Startfenster (gestochen scharf, unabhängig von der ico-Verarbeitung)
    public const string Png =
        "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAUZElEQVR4nO1de5CcVZX/nXPv14/pSeaVxDyJBCpCwoK7gSVGYRLlEZTwUHqEEmFBFnBXcbeE1S3LnTQ+kARkQZECRUHF3Z1ei0W3XA" +
        "El04oxEgK4RQYDCstDEhLIY57d/d17zv7xdff0TCYBdDrpCfOr6qrpm0z3N+d3z+887vm6gUlM4q0MOtgXUH9QQhrcvgiUAwQZklq+2yQBAMpGBwBkyR/Id36LE6CE9m6D3ApXXjnqoy+1kdETFVgO" +
        "plkpS1dsumPOIKAEkI73Fbx1CUirKe/2ReknY4VEyxkGOB+ky00Qn2niKYjrhRNd8PS3Zj2HTuVayJEd7xese3QqIwNFlvz8sx9v5lTzJUWyHzMmtpiNASQP9UPi83mhwFKMaSaA59CTrclmfWsRkF" +
        "aDTLTrF3T8/hKY2OdMkDoCWoS6fhElZWImw0wEGJtgdUMtAJBGGtkaXNJbhQBCWhlZ8rPP6VkYj6Vu5iCxEgghYa9jBhMzExGIGUQAMSkZC4JJAsD27d018QCuxYvWF5TQqYQs+cPOefrCeCz1aw4S" +
        "K8X3eUhRmMkSMxMTiAlglEggEBFUS3FyeW2u7hAnQCPjZUjmf3DLV2y88XsEbVXX54nYgIlBqBi7/AABYAKRAqRFAEB3ba7wEJagkvHbu8381me+w7GmCyXcI2xARMaUjc1U2u1Mo4gAQ0MwTC8AzJ" +
        "ixfNxTUOCQ9QAlAIR0lue1zP53E2+6UMPekJiY2FBZbsqSA8YwCUwghrKxpOIcMW0HgOwiTBLwBlGqaknmFY+928ZbPiThnpAYQbTL95acsuwM/0wgYwGm3aaB/wgAyEwS8MbQvs4gS37eqp41Jt7y" +
        "kcj4FFSMyyWNjzKdYekZ4Q1QtnEQ4w+brm/treXlHloEtK+zyK1w81b1XGzizdeo63XEsCPkZfTPY+o/C9sATPQEAG3vVFuLNgRwKAXhqFXg5py75ThSe5tK3hNpSfCrdnuVscvaPzoTAoMABYFy0Y" +
        "t31+yyDxEPiDKeuen1SRZ8l20sCTgQcyXgVmRnlAdEeX/1GtSYwEjY32+s/hIAclhes5b0oUFAe7dBhgT55utMrPlYlUHHzGasYDviMYYMgUlMPKUAHn5kzbSXatWEK2PiE5BWg9wKN/fsp043QepT" +
        "6npLRVaVvFTv8H2lnhVJAoiY2Jp7AKC9xjaa4AQoYdFqnXXmo9OYzDeJVImUiIlGyMs+0s291gHlIMG+2PsyJ8IfAUq51ajpAc3EJqC92yCTEWtSX+PYlHkqBRluqu1fakYWXmXPIG/jjQSiOx/JTO" +
        "tNd4GjfkTtMHGzoOhAxc07q+ciEzSdr67PsTEWjP0H26r1cmAGEQgQMjH2hd5drME3AKXs5toUX9WYoB4QtZYP+8D/LgDHblbJC5EakJZbySUtH5lm7kt+iAhKEJucwoC/eeMNjdvSXahp8C1jIhJA" +
        "SIMAJTX2ThMkm6FFJbZENgG2MbANwDYOsrFhInhvyRn2EBUbSxpf2PM8J+UmqFK2AzU3PjARJah0sDLvzCc/a+LTlqvb7TlIGNIhUN/vURjcARWHWHIKgqb5oMY5oLJnULXsVPV+GGqCBEsYXvNIZl" +
        "pvukdNFgdmOmJiHcqXcvLDznlqCRBfTySGjGEOt1Jxx28w1L8Lba1TEI9b7NzVj0LBo2nOIsRnLwNZCyYFmeH2MxsGoD5ItRop7P7hxjWt56XTarIHcDRlAnlAudp9IYnC4F0cszFV59m9RvmtOUxp" +
        "jOGaq87FScuORCIe4KU/7sKd3/s1fv6zx9BMQHL+chDJyCAMURNLsoSDrzj1V0GVsqtrH3irMXFiQKXa7b+OE83HqAw5Zhi3+7ewLPjKtR249MPvxPS2RjSm4jjumJm4Zc25OO30Jdj14pOQgZdANj" +
        "5KeoywjRM0/Pjja6e/nO44MIG3GhODgHRXVO2u+t3KqNrtc8SBMdKH/l1bccr7/gLt756LbTsdnBN4r+jtd1AFLr/kJDQkYyi89hy4lB1FLWn1QUOL8WHfNzde33Jve+c6eyClp4wJQIASspt11pm/" +
        "m0aG7yBSJQiTMQQZgPoQi4+aA1EtGTgysjUGhQIwe2YzZr6tGYWB3ZEEMYMgYuIp4wt7no6J/3Rnp3Ju9fIDbnyg/gkonW5lxJB+3QRT5qnkS9UuALZQEAaGiuUJhlG/rHDOo1BwYGPL5CjZQAH1lv" +
        "nS9Wun9/UsBtW64t0X6puAcsq5qudiE2/6sPp+R8aYqMUvoNhUxBMN+MXDW5DPA7EYlyRI4JxHUyNh42PP4+WtO9HQMhMwFoD6INlkJBz68obrpv4q3aUm23HgpaeM+iWgs1Ttrvrd4TDBzdCo2qVK" +
        "ZSWAnYLGty3EE0/8ATfdmkMQEFpaDJqmGkxvtXhs8w7c9PX7EUumEJ/xDqg4b5NN1uV3b2hsaL02Mv6BKbj2hTpNQ5XQA4Iq6dlbvm2ChiZ1Ax52uNHGRCB4mLbjMCW/E3d99+d4sudFnLL8aDQ2xr" +
        "HlmW348U8eR19fHtOPOR2moUUJIEjYb9RcmsuQ6+xUrtVR4xtFfRZi5bPdM3s+a5Kt16nb4yPpAZi5enwEbCwAD//q49izdQvC/ACIAIFB07SZmHr4iYi1LYBK0cdSbcYXdv3dxutbb2vvXGdzmeGx" +
        "9IOF+iMg3WWQ7fDzznrqeDKJXxF5QyRMhomIIgLMyK4mGwMyAUj6oIVdgHqYRCNManqU+0uhXO3+eOOatrNKxvfAgS26xkKdSZASkMWsMx9tAJk72diYSlGIDFVGR8q9nKqz3EhFiqCgEZxsjkgiAP" +
        "CALwjHkyzhwHax/gpAo1uP6sD4QL0F4SWbLLId3lDDdSY29ViVIUdseP8jJJVREgACkhCQAqAhiFTJWDE2TtDilZu+PGNrOn3gq939oT48IN1lsH06IXd8OOfMzWeYIHWV+n5H0aT+PtvIe000cGnw" +
        "ignEpUZbQ7MNC7u+uen6afce7JRzLBzcGJDuMsimpZyJzGu/+3hqPvE+tonZ0KKQGR4br+j9iCC89/Oq8RIxiUaGFLcEvnDC+oZpA1gNPVgF175wMCSIkO4yAIBshwdI5y+7ecVhS7/wQyRmPUg2OV" +
        "slr5Wz3arHWJPM5SPIyvRDtK5krQLqRN1l69dO70v3HLxqd384kB5ASHdxZPQI8969dhUpf5LInyrBTEct7wGR42iKed+7+/XWQXCxVKv1+Z3XblzT1tneqTaXoYOeco6FA0CAEtpXG+QyDgCOPPLm" +
        "eDizeC6UPwkyy4gIXqQXracRB4kpRD5qmJUOTMaaXtgXCWwYIPU22WQkHPh1KtF08oweaDYLOdgF175QwyCshHSWkSWPHNz09s7GZDj1giIKVzHHj1FVqA9FtVig5pM9BakWQkGJSynn6OPDUZlQZb" +
        "iqOgBDlU2M4AsDRt3HchlyqINqd3+oAQGdjHYwcuSQhV/wrrUzPOOj6vhyNrGFqg4S5j2IASkwGt4xiMScFqAAMNOIHf96U817jRrCm0SjdcXeqzetmfZUPWY9ozGOEtTJSPcQslkPAHOX3jjHsFyh" +
        "oL9lG5+pEkJ96KOtXZpq4MbdaDslwcYkKr36svRUG9uU+z8MMEZIU7kyjs52W4wUen+0cU3L2RPB+MC4eIASsJqAjCALzH/Xl45Sjl8O4KNkEtPgi5BwyIHAIIqyHxCgMoSmE5hNLEEIK8Yfc5K5ep" +
        "x89HAVA4CKiSVYwqFXxAZXHqihqvHAOBBACkDnL1vzToX5pJKczybeoL4ACQd9yfBV78OA5L02HjdE8ektQBEU3Tn3pieZh5+zsI1ZLQxcuekrLVvTaTXZTP3vfuDPIiCaUpi15Ma2IE63KOl5bGKB" +
        "uHxpx6sZ3vFlkEJDQmxmLxqPbiQ4opKs7DXJPDrYjh41LP3fSrVb3HXHprWt/9XeqTZbpynnWPjTC7F0lgFSE/dfNLHUBRBvJBz0iG5ttii1w0aAQKBgQKcuCZhNjEjHnt2sarztc5I5Mr6YRMr4Yt" +
        "+WeIu/Gp3KuUxtp5nHG392JczALqgA9Dp/ODHgi06nHFfgWEsjoag01j26b3CSuara9Sp66frPTO9DD6ieU86x8KcTkE0LoCRir/Wu/z/YJgO2yUjMFQ6oPuojQIrQxPw9lFzQFOl+eYL2zU4yV+RK" +
        "gmSTgRv60qNrmta3d66zB/rDlsYD45aGzlu25jQCXwLoWWwTDVHa6aK+O8EoxfrQdqphm2iornb/lJYDEcQmGllcvnsw2XT64sXw0dnuxNr9wPg04wgAvbj+nx54Yf3VF4jwcT4czKj4Z9jGmYOkUS" +
        "kWMOWvQraphtLNc/tsMb/uI8p6AIIAfk1PhorP7trEEyPp3BvjV4iluwwWbVZkMgIAc5femGRLHyAJL9Lkke/l1hNT6gccMdt97uw37A1QNhZkg20kxX/e8KWmu6NLmBjFVzVq0IzrZKQXU3XXc9YH" +
        "nj2dLd/SMKVhoSv2eiIwm+FjxtENtcp61dnv3uuACRLgWBzi8t+PafiPuczUV4dHTSaGHNXgPCAjJeNHff90l3nt/gX3f+Z93zl7247ga0GiydggToD6sXb6iPPe0UF4xDpDpaBS7JcgmbgwtPHfLO" +
        "3cvTLyANJo5KT+UdN2tGraAFnpf2rVKY0zwtvRtO2K+Cn/HZ8929yeakzOLhZ2e2ZmNryXN4zZbq5eM1XkQB1RYNU7+GLhhm0v//bzz9+9Il8voyf7Q813CRG0QfMdIHs4dhzxQKH74ZUfP3Xzqq2v" +
        "hf+WaJxmjDEEwI/Z4xnVcq5eq6SvIEDU+sKA+MKQcJC6esaMxb/4y79//vjI+EqoY2+omQeoluZle97X5kO7hYJ8q6aOFXPYJwyw9WnghU/E3n/63CPm2lsSiaCxWOhzxrAdK0PaX2BWFYh3UO+h3k" +
        "PComeTND7M531Y+PwTty64AQDa29fZXK7+vKF2O6O73QCA76f3m6Rp07wIpxYbCfc4oGEh8I4Hij/Z8PY59uX37u7Vh5JTZ1hiUkBldLOtrP/VvSKOph4iw4sAJQKgMC7fK+KKCWMb1h57+Zb7F124" +
        "6chcboWLzqK1robRakfA8tIHXDg9D0Wn4GZF8u0gOCuFIfH5ogJH/MvPvrH9ludu/NHn/u/5gc9ykKAgkWKFurHz/ypSoFARqArgBaql5yKAgtWFWhzc5Zjjp5kgvmHRRx67uDwEUBkKqAPUhADtBB" +
        "NlRB84ZTZCWqF7hgjBHINYM6AORMzMICnsckDLUjTN/8WrXQ/37dnRcHI+tJvjqTYLgo8+emCMvhBRZHDvoV6g4iueIOIh4qGqBBXr8nu8iLaxjd919PmP3n3UOQ+2Idvh64WE2njA8nYGAE9uhUnY" +
        "KX7IeWo4jMAW1XdREKmVfJ8oTQmAnbc++6/tl91z3k0fdMXCt4NkkyEbJ5DuHaChw4ZXX9r5HioeKMuRCNQLoGrU5dUV+j2Z+EVqGn9z5KqfnYpsh6+H4FybC9gxQwFAQ5wOp6qegeRMQKv6cyoAW5" +
        "CNsb5yH/zmbxUQm3HRcXMf+ummtQ1XFPLFjxhjXg2SzQZQTwQtxwMpGVulTIREP5ckSFUqZESeoQQREw7tdqp6BHH8/gVn/M+VyJAcbBLG/c1VQdSR9dq1NIkivQcDjkgCIpsC1Jc8QAHbABR7oc/e" +
        "Bd32oDPJVFy253cUCuYf7rjjdnrihoYfhPnepeKH7g9SUw2xIZDKCNmRkbtfvQzLki/LUfTvIh5Qsb445MUXSIVunbfivsUHm4Txn4pYDQKgRaEjjOh8PyRK8AxVwCYBNoA46CuPQF/6KdTvdLatyc" +
        "qg2+KG9LzEXz/4pOpP6QcvL7S5zNv+AGDlstWD15DhL7BJxsPBPU7F24rhK3LjSztfKsRABBAP9VohCKpGfNERJy0QLgGwGd3d0WTvQcD4E7A4TUAWEPNOY5hdKJ7gjT77SxAZaP824JVNkN5nBDaA" +
        "ndZk/Z7wJyY/9Dfxkx/eoevaLRE5AKWZntVYv7ph7bsyA93qh26z8aYl4cAOVe9VRXnY6DJMRoWcsiR5wGtEhjiogMUPKlHxSQDAjB0HrW80/gRM304AQCEvgBJQFIWNQV/4LXTrkwBCiIEPUimDGM" +
        "HtzH/VPvTQNZSBaFfa0IrscLFUGiMvdTk3tl/83HsKc1q+AAquJjbki/1ORexehi8FYNVhWZLKuvfEDUaKu7te6P7QY+jsZGQ6DqGb9EoBmDxmoKhQB6hTQC3UQVTjPkg1GnHySrHXdQTtD30aq6Ha" +
        "CaaO7JiGyHaQ7+xUzt19eH7Dl5uvkcLgSvHuGRObYlW8F+91mADZOzaIlgOyAIZ9sW8bafipeijKxp+AzZEHSFEUTj1CFS2Kl6J4S4atZeP7wnt5wC2Nn/FQVrvSBgAos38NzmRIAKX29nV241fn3G" +
        "9371jqC/3fZZM0RIbEOz9CdiraXyFCVVRViVQKVz6f69iGdJbL5xcHCzWIAZEHwNEGgD8REBsEDFjA5/1mhHSdPb/7HgDQrrTZ164fG6S5HFw6rSZ7J+0EcPGxl235OaBfNTbVFg7tdirOqBcanSWJ" +
        "eM+mwbr87tte7E7fV74Xbdz//jeJcXdBLb/m7UusyyeupxidAstPw+q9z/Zu/c+Fn/p9QTs7Gci87q7f/xspoQOMLPnFFz16BBD7OnFspRvaA3GhVxGjPozSURd6wBpfzD9VsPETXll22hAy0Ho4tD" +
        "ngGvjmd/3+Ud3zP/qCR65RpQwESZfv8yJe1TmFUCAiDuHQSc/nPrShXnY/UOsDmZKxtbOTsbiHkM4KUQ2Oz8tfzAPShed2n6AU3AI1S8tFmS8OFqTYe9kLufT368n4wMG+R2y8Uf5qqnSXWTDYmobg" +
        "JPHFvDh3zwsPnfVYvRn/0MS+2gp10HgbC4eWB1RQ/mrCLLB9OmH58pp/J+QkJjGJSUxiEpOYxCQmMYlJTGISk5jEJCYxiUlMYhKTmMQk6hT/D5ok9iUwHPHLAAAAAElFTkSuQmCC";

    static System.Drawing.Icon cached;

    public static System.Drawing.Icon Get()
    {
        if (cached != null) return cached;
        try
        {
            string exe = System.Environment.GetEnvironmentVariable("LEOSMINIBENCH_EXE");
            if (!string.IsNullOrEmpty(exe) && System.IO.File.Exists(exe)) { cached = System.Drawing.Icon.ExtractAssociatedIcon(exe); if (cached != null) return cached; }
        }
        catch { }
        try { cached = new System.Drawing.Icon(new System.IO.MemoryStream(System.Convert.FromBase64String(Ico))); } catch { cached = null; }
        return cached;
    }

    // Symbol in einer bestimmten Größe (z. B. 64 px für Kopfzeile und Startfenster)
    public static System.Drawing.Bitmap Image(int size)
    {
        try
        {
            using (System.Drawing.Image src = System.Drawing.Image.FromStream(new System.IO.MemoryStream(System.Convert.FromBase64String(Png))))
            {
                System.Drawing.Bitmap b = new System.Drawing.Bitmap(size, size);
                using (System.Drawing.Graphics g = System.Drawing.Graphics.FromImage(b))
                {
                    g.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
                    g.DrawImage(src, 0, 0, size, size);
                }
                return b;
            }
        }
        catch { return null; }
    }

    public static void SetAppId()
    {
        try { SetCurrentProcessExplicitAppUserModelID(AppId); } catch { }
    }
}

public static class StartLog
{
    public static string StatusFile { get { return System.Environment.GetEnvironmentVariable("LEOSMINIBENCH_START") ?? ""; } }

    public static void Phase(string text)
    {
        string f = StatusFile;
        if (f.Length == 0) return;
        try { System.IO.File.AppendAllText(f, System.DateTime.Now.Ticks.ToString(System.Globalization.CultureInfo.InvariantCulture) + "|O|" + text.Replace("|", "/") + "\r\n", System.Text.Encoding.UTF8); } catch { }
    }

    // Startfenster der exe schließen lassen
    public static void SignalReady()
    {
        string n = System.Environment.GetEnvironmentVariable("LEOSMINIBENCH_BEREIT") ?? "";
        if (n.Length == 0) return;
        try { using (System.Threading.EventWaitHandle h = System.Threading.EventWaitHandle.OpenExisting(n)) h.Set(); } catch { }
    }

    // Ort des Programms: Stick, Festplatte oder Netzlaufwerk (Laufwerk der exe, sonst des Skripts)
    public static string Place(string path, out string drive)
    {
        drive = "";
        try
        {
            string exe = System.Environment.GetEnvironmentVariable("LEOSMINIBENCH_EXE");
            string p = !string.IsNullOrEmpty(exe) ? exe : path;
            string root = System.IO.Path.GetPathRoot(System.IO.Path.GetFullPath(p));
            drive = root.TrimEnd('\\');
            System.IO.DriveInfo di = new System.IO.DriveInfo(root);
            switch (di.DriveType)
            {
                case System.IO.DriveType.Removable: return "Stick";
                case System.IO.DriveType.Fixed: return "Festplatte";
                case System.IO.DriveType.Network: return "Netzlaufwerk";
                default: return di.DriveType.ToString();
            }
        }
        catch { return "unbekannt"; }
    }

    // Statusdatei lesen und als Block an Minibench-Daten\Laufzeit\Start.log anhängen:
    //   START|Zeit|Version|Ort|Laufwerk|gesamt ms
    //   PHASE|ms seit dem Start der exe|Quelle|Text
    public static string Finish(string dataDir, string version, string scriptPath)
    {
        string f = StatusFile;
        if (f.Length == 0 || string.IsNullOrEmpty(dataDir) || !System.IO.File.Exists(f)) return "";
        try
        {
            string[] lines = System.IO.File.ReadAllLines(f, System.Text.Encoding.UTF8);
            long t0 = 0; System.Collections.Generic.List<string> ph = new System.Collections.Generic.List<string>();
            long last = 0;
            foreach (string l in lines)
            {
                string[] x = l.Split(new char[] { '|' }, 3);
                long t; if (x.Length < 3 || !long.TryParse(x[0], System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out t)) continue;
                if (t0 == 0) t0 = t;
                long ms = (t - t0) / 10000;
                last = ms;
                ph.Add("PHASE|" + ms.ToString(System.Globalization.CultureInfo.InvariantCulture) + "|" + x[1] + "|" + x[2]);
            }
            if (ph.Count == 0) return "";
            string drive; string place = Place(scriptPath, out drive);
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.Append("START|").Append(new System.DateTime(t0).ToString("yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture)).Append('|').Append(version).Append('|').Append(place).Append('|').Append(drive).Append('|').Append(last.ToString(System.Globalization.CultureInfo.InvariantCulture)).Append("\r\n");
            foreach (string p in ph) sb.Append(p).Append("\r\n");
            string dir = System.IO.Path.Combine(dataDir, "Laufzeit");
            System.IO.Directory.CreateDirectory(dir);
            string log = System.IO.Path.Combine(dir, "Start.log");
            // höchstens rund 200 KB behalten (die ältesten Starts fallen heraus)
            try
            {
                System.IO.FileInfo fi = new System.IO.FileInfo(log);
                if (fi.Exists && fi.Length > 200000)
                {
                    string all = System.IO.File.ReadAllText(log, System.Text.Encoding.UTF8);
                    int cut = all.IndexOf("START|", all.Length / 2, System.StringComparison.Ordinal);
                    if (cut > 0) System.IO.File.WriteAllText(log, all.Substring(cut), System.Text.Encoding.UTF8);
                }
            }
            catch { }
            System.IO.File.AppendAllText(log, sb.ToString(), System.Text.Encoding.UTF8);
            return log;
        }
        catch { return ""; }
    }
}
